import type { Task } from '../components/TaskTable'

export const DEMO_USER = { id: 0, name: 'Demo User', email: 'demo@example.com', role: 'admin' as const }

export const DEMO_FAMILY = [
  { id: 1, name: 'Bea' },
  { id: 2, name: 'Mark' },
  { id: 3, name: 'Hope' },
  { id: 4, name: 'Charles' },
]

export const DEMO_TASKS: Task[] = [
  {
    id: 1, email_id: 1,
    summary: 'Your water supplier has issued a final reminder for the outstanding balance on your account. Payment is due immediately to avoid interruption of service.',
    action: 'Pay the outstanding water bill of £142.50 online or by phone',
    due_date: '2026-05-25', is_upcoming: false, event_date: null,
    is_fyi_only: false, status: 'pending',
    assignee_name: 'Bea',
    categories: 'Bea, Mark', tags: 'utilities,water bill',
    from_address: 'billing@waterco.example.com', from_name: 'Water Co', sender: 'Water Co',
    subject: 'Final Reminder – Account Balance Outstanding',
    received_at: '2026-05-19T08:14:00Z',
    comment_count: 1, latest_comment: 'Set up direct debit to avoid this', latest_comment_by: 'Mark',
  },
  {
    id: 2, email_id: 2,
    summary: 'The scouts group has confirmed a place on the summer camp from 14–18 July.',
    action: null,
    due_date: null, is_upcoming: true, event_date: '2026-07-14',
    is_fyi_only: false, status: 'pending',
    assignee_name: null,
    categories: 'Bea, Hope', tags: 'scouts,camp,payment',
    from_address: 'admin@scoutsgroup.example.com', from_name: 'Local Scouts', sender: 'Local Scouts',
    subject: 'Summer Camp 2026 – Deposit Required',
    received_at: '2026-05-18T10:32:00Z',
    comment_count: 0, latest_comment: null, latest_comment_by: null,
  },
  {
    id: 3, email_id: 3,
    summary: 'The school has requested parents sign and return the consent form for the Year 9 geography field trip on 12 June.',
    action: 'Sign and return consent form for the geography field trip',
    due_date: '2026-05-30', is_upcoming: false, event_date: null,
    is_fyi_only: false, status: 'in_progress',
    assignee_name: 'Mark',
    categories: 'Mark, Charles', tags: 'school,field trip,consent form',
    from_address: 'office@secondaryschool.example.com', from_name: 'Secondary School', sender: 'Secondary School',
    subject: 'Year 9 Geography Field Trip – Consent Required',
    received_at: '2026-05-17T14:05:00Z',
    comment_count: 2, latest_comment: 'Form is on the kitchen counter', latest_comment_by: 'Mark',
  },
  {
    id: 4, email_id: 4,
    summary: 'Your annual boiler service is due. An engineer can visit on 3 or 6 June between 9am and 1pm. Booking confirmation required.',
    action: 'Book boiler service appointment for 3 or 6 June',
    due_date: '2026-05-28', is_upcoming: false, event_date: null,
    is_fyi_only: false, status: 'pending',
    assignee_name: 'Bea',
    categories: 'Bea, Mark', tags: 'boiler,service,home',
    from_address: 'service@energyco.example.com', from_name: 'Energy Co', sender: 'Energy Co',
    subject: 'Your Annual Boiler Service is Due',
    received_at: '2026-05-16T09:20:00Z',
    comment_count: 0, latest_comment: null, latest_comment_by: null,
  },
  {
    id: 5, email_id: 5,
    summary: 'The primary school is requesting volunteers for the summer fair on 21 June. Parents are asked to sign up for a one-hour slot.',
    action: 'Sign up for a volunteer slot at the summer fair on 21 June',
    due_date: '2026-06-10', is_upcoming: false, event_date: null,
    is_fyi_only: false, status: 'pending',
    assignee_name: null,
    categories: 'Bea, Hope', tags: 'school,summer fair,volunteer',
    from_address: 'office@primaryschool.example.com', from_name: 'Primary School', sender: 'Primary School',
    subject: 'Summer Fair 2026 – Volunteer Sign-up',
    received_at: '2026-05-15T11:45:00Z',
    comment_count: 0, latest_comment: null, latest_comment_by: null,
  },
  {
    id: 6, email_id: 6,
    summary: 'The piano teacher has moved this week\'s lesson from Tuesday to Thursday 29 May at the same time due to a scheduling conflict.',
    action: 'Note the change: piano lesson is Thursday 29 May at 4:30pm, not Tuesday',
    due_date: '2026-05-29', is_upcoming: false, event_date: null,
    is_fyi_only: false, status: 'pending',
    assignee_name: 'Mark',
    categories: 'Mark, Charles', tags: 'piano,lesson,schedule change',
    from_address: 'teacher@musiclessons.example.com', from_name: 'Music Teacher', sender: 'Music Teacher',
    subject: 'Piano Lesson Rescheduled – Thursday This Week',
    received_at: '2026-05-19T17:02:00Z',
    comment_count: 0, latest_comment: null, latest_comment_by: null,
  },
  {
    id: 7, email_id: 7,
    summary: 'Your car insurance policy renews on 15 July. The renewal quote has increased compared to last year.',
    action: 'Compare car insurance quotes before 15 July renewal',
    due_date: '2026-07-10', is_upcoming: false, event_date: null,
    is_fyi_only: false, status: 'pending',
    assignee_name: 'Bea',
    categories: 'Bea, Mark', tags: 'insurance,car,renewal',
    from_address: 'renewals@insuranceco.example.com', from_name: 'Insurance Co', sender: 'Insurance Co',
    subject: 'Your Car Insurance Renews on 15 July – Review Your Quote',
    received_at: '2026-05-14T08:00:00Z',
    comment_count: 0, latest_comment: null, latest_comment_by: null,
  },
  {
    id: 8, email_id: 8,
    summary: 'The tax authority has confirmed receipt of the self-assessment return. A tax refund will be paid within 5 working days.',
    action: null,
    due_date: null, is_upcoming: false, event_date: null,
    is_fyi_only: true, status: 'pending',
    assignee_name: 'Bea',
    categories: 'Bea, Mark', tags: 'tax,refund',
    from_address: 'noreply@taxauthority.example.com', from_name: 'Tax Authority', sender: 'Tax Authority',
    subject: 'Self Assessment – Tax Return Received',
    received_at: '2026-05-13T12:30:00Z',
    comment_count: 0, latest_comment: null, latest_comment_by: null,
  },
  {
    id: 9, email_id: 9,
    summary: 'The rugby club newsletter covers the end-of-season presentation evening on 28 May and the upcoming summer training schedule.',
    action: null,
    due_date: null, is_upcoming: false, event_date: null,
    is_fyi_only: true, status: 'pending',
    assignee_name: null,
    categories: 'Mark, Charles', tags: 'rugby,newsletter,presentation',
    from_address: 'news@rugbyclub.example.com', from_name: 'Rugby Club', sender: 'Rugby Club',
    subject: 'May Newsletter – Presentation Evening & Summer Training',
    received_at: '2026-05-12T09:00:00Z',
    comment_count: 0, latest_comment: null, latest_comment_by: null,
  },
  {
    id: 10, email_id: 10,
    summary: 'Your music streaming service has raised the family plan price by £2 per month, effective from the next billing date on 1 June.',
    action: null,
    due_date: null, is_upcoming: false, event_date: null,
    is_fyi_only: true, status: 'pending',
    assignee_name: null,
    categories: 'Bea, Mark', tags: 'subscription,price increase',
    from_address: 'no-reply@streamingservice.example.com', from_name: 'Streaming Service', sender: 'Streaming Service',
    subject: 'Important Update to Your Family Plan',
    received_at: '2026-05-11T14:20:00Z',
    comment_count: 0, latest_comment: null, latest_comment_by: null,
  },
]

export const DEMO_EMAILS = [
  { id: 1, received_at: '2026-05-19T08:14:00Z', from_address: 'billing@waterco.example.com', from_name: 'Water Co', subject: 'Final Reminder – Account Balance Outstanding', processed: true },
  { id: 2, received_at: '2026-05-18T10:32:00Z', from_address: 'admin@scoutsgroup.example.com', from_name: 'Local Scouts', subject: 'Summer Camp 2026 – Deposit Required', processed: true },
  { id: 3, received_at: '2026-05-17T14:05:00Z', from_address: 'office@secondaryschool.example.com', from_name: 'Secondary School', subject: 'Year 9 Geography Field Trip – Consent Required', processed: true },
  { id: 4, received_at: '2026-05-16T09:20:00Z', from_address: 'service@energyco.example.com', from_name: 'Energy Co', subject: 'Your Annual Boiler Service is Due', processed: true },
  { id: 5, received_at: '2026-05-15T11:45:00Z', from_address: 'office@primaryschool.example.com', from_name: 'Primary School', subject: 'Summer Fair 2026 – Volunteer Sign-up', processed: true },
  { id: 6, received_at: '2026-05-19T17:02:00Z', from_address: 'teacher@musiclessons.example.com', from_name: 'Music Teacher', subject: 'Piano Lesson Rescheduled – Thursday This Week', processed: true },
  { id: 7, received_at: '2026-05-14T08:00:00Z', from_address: 'renewals@insuranceco.example.com', from_name: 'Insurance Co', subject: 'Your Car Insurance Renews on 15 July – Review Your Quote', processed: true },
  { id: 8, received_at: '2026-05-13T12:30:00Z', from_address: 'noreply@taxauthority.example.com', from_name: 'Tax Authority', subject: 'Self Assessment – Tax Return Received', processed: true },
  { id: 9, received_at: '2026-05-12T09:00:00Z', from_address: 'news@rugbyclub.example.com', from_name: 'Rugby Club', subject: 'May Newsletter – Presentation Evening & Summer Training', processed: true },
  { id: 10, received_at: '2026-05-11T14:20:00Z', from_address: 'no-reply@streamingservice.example.com', from_name: 'Streaming Service', subject: 'Important Update to Your Family Plan', processed: true },
]

export const DEMO_EMAIL_BODIES: Record<number, { body_text: string }> = {
  1: { body_text: `Dear Customer,\n\nThis is a final reminder that your account has an outstanding balance of £142.50.\n\nPayment is now overdue and must be received within 5 days to avoid interruption to your water supply.\n\nYou can pay:\n• Online at waterco.example.com/pay\n• By phone on 0800 000 0000\n• By setting up a Direct Debit to avoid future reminders\n\nIf you have already paid, please disregard this notice.\n\nWater Co Customer Services` },
  2: { body_text: `Dear Parents,\n\nWe are delighted to confirm a place on the Local Scouts Summer Camp 2026, taking place 14–18 July.\n\nTo secure the place, a non-refundable deposit of £75 is required by 1 June 2026. The total camp cost is £195, with the remaining £120 due by 30 June.\n\nPayment details will be provided separately by your group leader.\n\nKit list and further details to follow.\n\nYours in Scouting,\nGroup Scout Leader` },
  3: { body_text: `Dear Parent/Guardian,\n\nYear 9 Geography Field Trip – 12 June 2026\n\nPlease complete and return the attached consent form by Friday 30 May.\n\nCost: £45 (includes transport and entrance fees)\nDeparture: 7:30am from the main school gate\nReturn: approximately 6:30pm\n\nStudents should bring a packed lunch, waterproof clothing and suitable footwear.\n\nPayment can be made via the school's online payment system.\n\nMany thanks,\nHead of Geography` },
  4: { body_text: `Dear Customer,\n\nYour annual boiler service is now due.\n\nOur engineer can attend on:\n• Tuesday 3 June, 9am–1pm\n• Friday 6 June, 9am–1pm\n\nPlease call 0333 000 0000 or reply to this email to confirm your preferred date.\n\nAs a plan customer, this service is included at no extra cost.\n\nKind regards,\nEnergy Co Home Services` },
  5: { body_text: `Dear Families,\n\nSummer Fair – Saturday 21 June, 12–4pm\n\nWe need parent volunteers to help make this year's fair a success! We're looking for helpers for one-hour slots throughout the day.\n\nRoles include:\n• Tombola\n• BBQ assistance\n• Face painting support\n• Car park marshalling\n\nPlease sign up via the school website.\n\nAll volunteers receive complimentary entry and a free drink!\n\nWith thanks,\nThe PTA` },
  6: { body_text: `Hi,\n\nJust a quick note to let you know I need to move this week's lesson.\n\nDue to a prior commitment I'm unable to do Tuesday 27 May as usual. Could we switch to Thursday 29 May at the same time, 4:30pm?\n\nPlease let me know if that works and I'll confirm.\n\nMany thanks,\nMusic Teacher` },
  7: { body_text: `Dear Customer,\n\nYour car insurance policy is due for renewal on 15 July 2026.\n\nYour renewal quote is higher than last year's premium. We recommend comparing quotes before your renewal date.\n\nIf you'd like to accept this quote, no action is needed – your policy will renew automatically.\n\nTo make changes or cancel, please contact us by 14 July.\n\nInsurance Co` },
  8: { body_text: `Dear Customer,\n\nThank you for submitting your Self Assessment tax return.\n\nWe have calculated that you are due a repayment. This will be paid to your nominated bank account within 5 working days.\n\nIf you have any questions, please contact the Self Assessment helpline.\n\nHM Tax Authority` },
  9: { body_text: `Rugby Club – May Newsletter\n\nEnd of Season Presentation Evening\nJoin us on Wednesday 28 May at 7pm in the clubhouse to celebrate another great season. Trophies, player awards, and end-of-season speeches.\n\nSummer Training\nSummer training runs every Tuesday from 3 June, 6:30–8pm. All age groups welcome.\n\nKit Collection\nEnd-of-season kit collection will take place at the presentation evening. Please ensure all club kit is returned clean.\n\nSee you on the pitch!\nRugby Club Junior Section` },
  10: { body_text: `Hi,\n\nWe're writing to let you know about an upcoming change to your Family streaming plan.\n\nFrom 1 June 2026, the monthly price will increase by £2.00 per month.\n\nThis change will be reflected in your next billing statement.\n\nYou can continue to enjoy content for up to 6 family members living at the same address.\n\nIf you have any questions, visit our help centre.\n\nThe Streaming Service Team` },
}
