import type { Task } from '../components/TaskTable'

export const DEMO_USER = { id: 0, name: 'Demo User', email: 'demo@example.com', role: 'admin' as const }

export const DEMO_TASKS: Task[] = [
  {
    id: 1, email_id: 1,
    summary: 'Thames Water has issued a final reminder for the outstanding balance on your account. Payment is due immediately to avoid interruption of service.',
    action: 'Pay the outstanding water bill of £142.50 online or by phone',
    due_date: '2026-05-25',
    is_fyi_only: false, status: 'pending',
    assignee_name: 'Darren',
    categories: 'Household', tags: 'utilities,water bill',
    from_address: 'billing@thameswater.co.uk', from_name: 'Thames Water',
    subject: 'Final Reminder – Account Balance Outstanding',
    received_at: '2026-05-19T08:14:00Z',
    comment_count: 1, latest_comment: 'Set up direct debit to avoid this', latest_comment_by: 'Lorraine',
  },
  {
    id: 2, email_id: 2,
    summary: 'St Albans Scouts has confirmed Thomas\'s place on the summer camp from 14–18 July. A deposit of £75 is required by 1 June to secure the booking.',
    action: 'Pay £75 deposit for scouts summer camp by 1 June',
    due_date: '2026-06-01',
    is_fyi_only: false, status: 'pending',
    assignee_name: null,
    categories: 'Thomas', tags: 'scouts,camp,payment',
    from_address: 'admin@stalbansscouts.org.uk', from_name: 'St Albans Scouts',
    subject: 'Summer Camp 2026 – Deposit Required',
    received_at: '2026-05-18T10:32:00Z',
    comment_count: 0, latest_comment: null, latest_comment_by: null,
  },
  {
    id: 3, email_id: 3,
    summary: 'Hitchin Boys School has requested parents sign and return the consent form for the Year 9 geography field trip to the Peak District on 12 June.',
    action: 'Sign and return consent form for Thomas\'s geography field trip',
    due_date: '2026-05-30',
    is_fyi_only: false, status: 'in_progress',
    assignee_name: 'Lorraine',
    categories: 'Thomas', tags: 'school,field trip,consent form',
    from_address: 'office@hitchinboys.herts.sch.uk', from_name: 'Hitchin Boys School',
    subject: 'Year 9 Geography Field Trip – Consent Required',
    received_at: '2026-05-17T14:05:00Z',
    comment_count: 2, latest_comment: 'Form is on the kitchen counter', latest_comment_by: 'Lorraine',
  },
  {
    id: 4, email_id: 4,
    summary: 'British Gas annual boiler service is due. An engineer can visit on 3 or 6 June between 9am and 1pm. Booking confirmation required.',
    action: 'Book boiler service appointment for 3 or 6 June',
    due_date: '2026-05-28',
    is_fyi_only: false, status: 'pending',
    assignee_name: 'Darren',
    categories: 'Household', tags: 'boiler,service,british gas',
    from_address: 'service@britishgas.co.uk', from_name: 'British Gas',
    subject: 'Your Annual Boiler Service is Due',
    received_at: '2026-05-16T09:20:00Z',
    comment_count: 0, latest_comment: null, latest_comment_by: null,
  },
  {
    id: 5, email_id: 5,
    summary: 'William Ransom Primary School is requesting volunteers for the summer fair on 21 June. Parents are asked to sign up for a one-hour slot.',
    action: 'Sign up for a volunteer slot at the summer fair on 21 June',
    due_date: '2026-06-10',
    is_fyi_only: false, status: 'pending',
    assignee_name: null,
    categories: 'Matthew', tags: 'school,summer fair,volunteer',
    from_address: 'office@williamransom.herts.sch.uk', from_name: 'William Ransom Primary School',
    subject: 'Summer Fair 2026 – Volunteer Sign-up',
    received_at: '2026-05-15T11:45:00Z',
    comment_count: 0, latest_comment: null, latest_comment_by: null,
  },
  {
    id: 6, email_id: 6,
    summary: 'Matthew\'s piano teacher has moved his Tuesday lesson to Thursday 29 May at the same time (4:30pm) due to a scheduling conflict.',
    action: 'Note the change: Matthew\'s piano lesson is Thursday 29 May at 4:30pm, not Tuesday',
    due_date: '2026-05-29',
    is_fyi_only: false, status: 'pending',
    assignee_name: 'Lorraine',
    categories: 'Matthew', tags: 'piano,lesson,schedule change',
    from_address: 'sarah.j.piano@gmail.com', from_name: 'Sarah Jones',
    subject: 'Piano Lesson Rescheduled – Thursday This Week',
    received_at: '2026-05-19T17:02:00Z',
    comment_count: 0, latest_comment: null, latest_comment_by: null,
  },
  {
    id: 7, email_id: 7,
    summary: 'The family car insurance policy renews on 15 July. Admiral has quoted £924 for renewal, up from £811 last year.',
    action: 'Compare car insurance quotes before 15 July renewal',
    due_date: '2026-07-10',
    is_fyi_only: false, status: 'pending',
    assignee_name: 'Darren',
    categories: 'Household', tags: 'insurance,car,renewal',
    from_address: 'renewals@admiral.com', from_name: 'Admiral Insurance',
    subject: 'Your Car Insurance Renews on 15 July – Review Your Quote',
    received_at: '2026-05-14T08:00:00Z',
    comment_count: 0, latest_comment: null, latest_comment_by: null,
  },
  {
    id: 8, email_id: 8,
    summary: 'HMRC has confirmed receipt of the 2024/25 self-assessment tax return. A tax refund of £320 will be paid within 5 working days.',
    action: null,
    due_date: null,
    is_fyi_only: true, status: 'pending',
    assignee_name: 'Darren',
    categories: 'Household', tags: 'tax,hmrc,refund',
    from_address: 'noreply@hmrc.gov.uk', from_name: 'HMRC',
    subject: 'Self Assessment – Tax Return Received',
    received_at: '2026-05-13T12:30:00Z',
    comment_count: 0, latest_comment: null, latest_comment_by: null,
  },
  {
    id: 9, email_id: 9,
    summary: 'Thomas\'s rugby club newsletter for May covers the end-of-season presentation evening on 28 May and upcoming summer training schedule.',
    action: null,
    due_date: null,
    is_fyi_only: true, status: 'pending',
    assignee_name: null,
    categories: 'Thomas', tags: 'rugby,newsletter,presentation',
    from_address: 'news@hitchinrugby.co.uk', from_name: 'Hitchin RFC',
    subject: 'May Newsletter – Presentation Evening & Summer Training',
    received_at: '2026-05-12T09:00:00Z',
    comment_count: 0, latest_comment: null, latest_comment_by: null,
  },
  {
    id: 10, email_id: 10,
    summary: 'Spotify has raised the family plan price from £17.99 to £19.99 per month, effective from the next billing date on 1 June.',
    action: null,
    due_date: null,
    is_fyi_only: true, status: 'pending',
    assignee_name: null,
    categories: 'Household', tags: 'spotify,subscription,price increase',
    from_address: 'no-reply@spotify.com', from_name: 'Spotify',
    subject: 'Important Update to Your Spotify Family Plan',
    received_at: '2026-05-11T14:20:00Z',
    comment_count: 0, latest_comment: null, latest_comment_by: null,
  },
]

export const DEMO_EMAILS = [
  { id: 1, received_at: '2026-05-19T08:14:00Z', from_address: 'billing@thameswater.co.uk', from_name: 'Thames Water', subject: 'Final Reminder – Account Balance Outstanding', processed: true },
  { id: 2, received_at: '2026-05-18T10:32:00Z', from_address: 'admin@stalbansscouts.org.uk', from_name: 'St Albans Scouts', subject: 'Summer Camp 2026 – Deposit Required', processed: true },
  { id: 3, received_at: '2026-05-17T14:05:00Z', from_address: 'office@hitchinboys.herts.sch.uk', from_name: 'Hitchin Boys School', subject: 'Year 9 Geography Field Trip – Consent Required', processed: true },
  { id: 4, received_at: '2026-05-16T09:20:00Z', from_address: 'service@britishgas.co.uk', from_name: 'British Gas', subject: 'Your Annual Boiler Service is Due', processed: true },
  { id: 5, received_at: '2026-05-15T11:45:00Z', from_address: 'office@williamransom.herts.sch.uk', from_name: 'William Ransom Primary School', subject: 'Summer Fair 2026 – Volunteer Sign-up', processed: true },
  { id: 6, received_at: '2026-05-19T17:02:00Z', from_address: 'sarah.j.piano@gmail.com', from_name: 'Sarah Jones', subject: 'Piano Lesson Rescheduled – Thursday This Week', processed: true },
  { id: 7, received_at: '2026-05-14T08:00:00Z', from_address: 'renewals@admiral.com', from_name: 'Admiral Insurance', subject: 'Your Car Insurance Renews on 15 July – Review Your Quote', processed: true },
  { id: 8, received_at: '2026-05-13T12:30:00Z', from_address: 'noreply@hmrc.gov.uk', from_name: 'HMRC', subject: 'Self Assessment – Tax Return Received', processed: true },
  { id: 9, received_at: '2026-05-12T09:00:00Z', from_address: 'news@hitchinrugby.co.uk', from_name: 'Hitchin RFC', subject: 'May Newsletter – Presentation Evening & Summer Training', processed: true },
  { id: 10, received_at: '2026-05-11T14:20:00Z', from_address: 'no-reply@spotify.com', from_name: 'Spotify', subject: 'Important Update to Your Spotify Family Plan', processed: true },
]

export const DEMO_EMAIL_BODIES: Record<number, { body_text: string }> = {
  1: { body_text: `Dear Customer,\n\nThis is a final reminder that your account has an outstanding balance of £142.50.\n\nPayment is now overdue and must be received within 5 days to avoid interruption to your water supply.\n\nYou can pay:\n• Online at thameswater.co.uk/pay\n• By phone on 0800 980 8800\n• By Direct Debit to avoid future reminders\n\nIf you have already paid, please disregard this notice.\n\nThames Water Customer Services` },
  2: { body_text: `Dear Parents,\n\nWe are delighted to confirm Thomas's place on the St Albans Scouts Summer Camp 2026, taking place 14–18 July at Gilwell Park, Essex.\n\nTo secure his place, a non-refundable deposit of £75 is required by 1 June 2026.\n\nThe total camp cost is £195, with the remaining £120 due by 30 June.\n\nPlease pay via BACS:\nAccount: St Albans Scouts\nSort code: 30-96-26\nAccount number: 12345678\nReference: THOMAS-CAMP26\n\nKit list and further details to follow.\n\nYours in Scouting,\nGroup Scout Leader` },
  3: { body_text: `Dear Parent/Guardian,\n\nYear 9 Geography Field Trip – Peak District, 12 June 2026\n\nPlease complete and return the attached consent form by Friday 30 May.\n\nCost: £45 (includes coach travel and entrance fees)\nDeparture: 7:30am from the main school gate\nReturn: approximately 6:30pm\n\nStudents should bring a packed lunch, waterproof clothing and suitable footwear.\n\nPayment can be made via ParentPay.\n\nMany thanks,\nMrs Clarke\nHead of Geography` },
  4: { body_text: `Dear Mr Johnston,\n\nYour annual boiler service is now due.\n\nOur engineer can attend on:\n• Tuesday 3 June, 9am–1pm\n• Friday 6 June, 9am–1pm\n\nPlease call 0333 202 9802 or reply to this email to confirm your preferred date.\n\nAs a HomeCare customer, this service is included in your plan at no extra cost.\n\nKind regards,\nBritish Gas Home Services` },
  5: { body_text: `Dear Families,\n\nWilliam Ransom Summer Fair – Saturday 21 June, 12–4pm\n\nWe need parent volunteers to help make this year's fair a success! We're looking for helpers for one-hour slots throughout the day.\n\nRoles include:\n• Tombola\n• BBQ assistance\n• Face painting support\n• Car park marshalling\n\nPlease sign up at: williamransom.co.uk/summerfair\n\nAll volunteers receive complimentary entry and a free drink!\n\nWith thanks,\nThe PTA` },
  6: { body_text: `Hi,\n\nJust a quick note to let you know I need to move Matthew's lesson this week.\n\nDue to a prior commitment I'm unable to do Tuesday 27 May as usual. Could we switch to Thursday 29 May at the same time, 4:30pm?\n\nPlease let me know if that works and I'll confirm.\n\nMany thanks,\nSarah` },
  7: { body_text: `Dear Mr Johnston,\n\nYour car insurance policy (ADM-2847361) is due for renewal on 15 July 2026.\n\nYour renewal quote: £924.00\nLast year's premium: £811.00\n\nWe recommend comparing quotes at comparison sites before your renewal date. If you'd like to accept this quote, no action is needed – your policy will renew automatically.\n\nTo make changes or cancel, please contact us by 14 July.\n\nAdmiral Insurance` },
  8: { body_text: `Dear Mr Johnston,\n\nThank you for submitting your 2024 to 2025 Self Assessment tax return.\n\nWe have calculated that you are due a repayment of £320.00. This will be paid to your nominated bank account within 5 working days.\n\nYour Unique Taxpayer Reference: 1234 56789\n\nIf you have any questions, please contact HMRC Self Assessment on 0300 200 3310.\n\nHM Revenue & Customs` },
  9: { body_text: `Hitchin RFC – May Newsletter\n\nEnd of Season Presentation Evening\nJoin us on Wednesday 28 May at 7pm in the clubhouse to celebrate another great season. Trophies, player awards, and end-of-season speeches.\n\nSummer Training\nSummer training runs every Tuesday from 3 June, 6:30–8pm at Taylors Hill. All age groups welcome.\n\nKit Collection\nEnd-of-season kit collection will take place at the presentation evening. Please ensure all club kit is returned clean.\n\nSee you on the pitch!\nHitchin RFC Junior Section` },
  10: { body_text: `Hi Darren,\n\nWe're writing to let you know about an upcoming change to your Spotify Premium Family plan.\n\nFrom 1 June 2026, the price of Spotify Premium Family will increase from £17.99 to £19.99 per month.\n\nThis change will be reflected in your next billing statement.\n\nYou can continue to enjoy music for up to 6 family members living at the same address.\n\nIf you have any questions, visit spotify.com/account.\n\nThe Spotify Team` },
}
